/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	manifestintegrityexemptionv1 "github.com/open-cluster-management/integrity-shield/logging/pkg/apis/manifestintegrityexemption/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeManifestIntegrityExemptions implements ManifestIntegrityExemptionInterface
type FakeManifestIntegrityExemptions struct {
	Fake *FakeApisV1
	ns   string
}

var manifestintegrityexemptionsResource = schema.GroupVersionResource{Group: "apis.integrityshield.io", Version: "v1", Resource: "manifestintegrityexemptions"}

var manifestintegrityexemptionsKind = schema.GroupVersionKind{Group: "apis.integrityshield.io", Version: "v1", Kind: "ManifestIntegrityExemption"}

// Get takes name of the manifestIntegrityExemption, and returns the corresponding manifestIntegrityExemption object, and an error if there is any.
func (c *FakeManifestIntegrityExemptions) Get(ctx context.Context, name string, options v1.GetOptions) (result *manifestintegrityexemptionv1.ManifestIntegrityExemption, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(manifestintegrityexemptionsResource, c.ns, name), &manifestintegrityexemptionv1.ManifestIntegrityExemption{})

	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegrityexemptionv1.ManifestIntegrityExemption), err
}

// List takes label and field selectors, and returns the list of ManifestIntegrityExemptions that match those selectors.
func (c *FakeManifestIntegrityExemptions) List(ctx context.Context, opts v1.ListOptions) (result *manifestintegrityexemptionv1.ManifestIntegrityExemptionList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(manifestintegrityexemptionsResource, manifestintegrityexemptionsKind, c.ns, opts), &manifestintegrityexemptionv1.ManifestIntegrityExemptionList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &manifestintegrityexemptionv1.ManifestIntegrityExemptionList{ListMeta: obj.(*manifestintegrityexemptionv1.ManifestIntegrityExemptionList).ListMeta}
	for _, item := range obj.(*manifestintegrityexemptionv1.ManifestIntegrityExemptionList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested manifestIntegrityExemptions.
func (c *FakeManifestIntegrityExemptions) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(manifestintegrityexemptionsResource, c.ns, opts))

}

// Create takes the representation of a manifestIntegrityExemption and creates it.  Returns the server's representation of the manifestIntegrityExemption, and an error, if there is any.
func (c *FakeManifestIntegrityExemptions) Create(ctx context.Context, manifestIntegrityExemption *manifestintegrityexemptionv1.ManifestIntegrityExemption, opts v1.CreateOptions) (result *manifestintegrityexemptionv1.ManifestIntegrityExemption, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(manifestintegrityexemptionsResource, c.ns, manifestIntegrityExemption), &manifestintegrityexemptionv1.ManifestIntegrityExemption{})

	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegrityexemptionv1.ManifestIntegrityExemption), err
}

// Update takes the representation of a manifestIntegrityExemption and updates it. Returns the server's representation of the manifestIntegrityExemption, and an error, if there is any.
func (c *FakeManifestIntegrityExemptions) Update(ctx context.Context, manifestIntegrityExemption *manifestintegrityexemptionv1.ManifestIntegrityExemption, opts v1.UpdateOptions) (result *manifestintegrityexemptionv1.ManifestIntegrityExemption, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(manifestintegrityexemptionsResource, c.ns, manifestIntegrityExemption), &manifestintegrityexemptionv1.ManifestIntegrityExemption{})

	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegrityexemptionv1.ManifestIntegrityExemption), err
}

// Delete takes name of the manifestIntegrityExemption and deletes it. Returns an error if one occurs.
func (c *FakeManifestIntegrityExemptions) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(manifestintegrityexemptionsResource, c.ns, name), &manifestintegrityexemptionv1.ManifestIntegrityExemption{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeManifestIntegrityExemptions) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(manifestintegrityexemptionsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &manifestintegrityexemptionv1.ManifestIntegrityExemptionList{})
	return err
}

// Patch applies the patch and returns the patched manifestIntegrityExemption.
func (c *FakeManifestIntegrityExemptions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *manifestintegrityexemptionv1.ManifestIntegrityExemption, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(manifestintegrityexemptionsResource, c.ns, name, pt, data, subresources...), &manifestintegrityexemptionv1.ManifestIntegrityExemption{})

	if obj == nil {
		return nil, err
	}
	return obj.(*manifestintegrityexemptionv1.ManifestIntegrityExemption), err
}
