/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	manifestintegrityexemptionv1 "github.com/open-cluster-management/integrity-shield/logging/pkg/apis/manifestintegrityexemption/v1"
	versioned "github.com/open-cluster-management/integrity-shield/logging/pkg/client/manifestintegrityexemption/clientset/versioned"
	internalinterfaces "github.com/open-cluster-management/integrity-shield/logging/pkg/client/manifestintegrityexemption/informers/externalversions/internalinterfaces"
	v1 "github.com/open-cluster-management/integrity-shield/logging/pkg/client/manifestintegrityexemption/listers/manifestintegrityexemption/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ManifestIntegrityExemptionInformer provides access to a shared informer and lister for
// ManifestIntegrityExemptions.
type ManifestIntegrityExemptionInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.ManifestIntegrityExemptionLister
}

type manifestIntegrityExemptionInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewManifestIntegrityExemptionInformer constructs a new informer for ManifestIntegrityExemption type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewManifestIntegrityExemptionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredManifestIntegrityExemptionInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredManifestIntegrityExemptionInformer constructs a new informer for ManifestIntegrityExemption type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredManifestIntegrityExemptionInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApisV1().ManifestIntegrityExemptions(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ApisV1().ManifestIntegrityExemptions(namespace).Watch(context.TODO(), options)
			},
		},
		&manifestintegrityexemptionv1.ManifestIntegrityExemption{},
		resyncPeriod,
		indexers,
	)
}

func (f *manifestIntegrityExemptionInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredManifestIntegrityExemptionInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *manifestIntegrityExemptionInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&manifestintegrityexemptionv1.ManifestIntegrityExemption{}, f.defaultInformer)
}

func (f *manifestIntegrityExemptionInformer) Lister() v1.ManifestIntegrityExemptionLister {
	return v1.NewManifestIntegrityExemptionLister(f.Informer().GetIndexer())
}
