/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	v1 "github.com/open-cluster-management/integrity-shield/logging/pkg/apis/manifestintegrityexemption/v1"
	scheme "github.com/open-cluster-management/integrity-shield/logging/pkg/client/manifestintegrityexemption/clientset/versioned/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ManifestIntegrityExemptionsGetter has a method to return a ManifestIntegrityExemptionInterface.
// A group's client should implement this interface.
type ManifestIntegrityExemptionsGetter interface {
	ManifestIntegrityExemptions(namespace string) ManifestIntegrityExemptionInterface
}

// ManifestIntegrityExemptionInterface has methods to work with ManifestIntegrityExemption resources.
type ManifestIntegrityExemptionInterface interface {
	Create(ctx context.Context, manifestIntegrityExemption *v1.ManifestIntegrityExemption, opts metav1.CreateOptions) (*v1.ManifestIntegrityExemption, error)
	Update(ctx context.Context, manifestIntegrityExemption *v1.ManifestIntegrityExemption, opts metav1.UpdateOptions) (*v1.ManifestIntegrityExemption, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ManifestIntegrityExemption, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ManifestIntegrityExemptionList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ManifestIntegrityExemption, err error)
	ManifestIntegrityExemptionExpansion
}

// manifestIntegrityExemptions implements ManifestIntegrityExemptionInterface
type manifestIntegrityExemptions struct {
	client rest.Interface
	ns     string
}

// newManifestIntegrityExemptions returns a ManifestIntegrityExemptions
func newManifestIntegrityExemptions(c *ApisV1Client, namespace string) *manifestIntegrityExemptions {
	return &manifestIntegrityExemptions{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the manifestIntegrityExemption, and returns the corresponding manifestIntegrityExemption object, and an error if there is any.
func (c *manifestIntegrityExemptions) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ManifestIntegrityExemption, err error) {
	result = &v1.ManifestIntegrityExemption{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("manifestintegrityexemptions").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ManifestIntegrityExemptions that match those selectors.
func (c *manifestIntegrityExemptions) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ManifestIntegrityExemptionList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ManifestIntegrityExemptionList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("manifestintegrityexemptions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested manifestIntegrityExemptions.
func (c *manifestIntegrityExemptions) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("manifestintegrityexemptions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a manifestIntegrityExemption and creates it.  Returns the server's representation of the manifestIntegrityExemption, and an error, if there is any.
func (c *manifestIntegrityExemptions) Create(ctx context.Context, manifestIntegrityExemption *v1.ManifestIntegrityExemption, opts metav1.CreateOptions) (result *v1.ManifestIntegrityExemption, err error) {
	result = &v1.ManifestIntegrityExemption{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("manifestintegrityexemptions").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(manifestIntegrityExemption).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a manifestIntegrityExemption and updates it. Returns the server's representation of the manifestIntegrityExemption, and an error, if there is any.
func (c *manifestIntegrityExemptions) Update(ctx context.Context, manifestIntegrityExemption *v1.ManifestIntegrityExemption, opts metav1.UpdateOptions) (result *v1.ManifestIntegrityExemption, err error) {
	result = &v1.ManifestIntegrityExemption{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("manifestintegrityexemptions").
		Name(manifestIntegrityExemption.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(manifestIntegrityExemption).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the manifestIntegrityExemption and deletes it. Returns an error if one occurs.
func (c *manifestIntegrityExemptions) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("manifestintegrityexemptions").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *manifestIntegrityExemptions) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("manifestintegrityexemptions").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched manifestIntegrityExemption.
func (c *manifestIntegrityExemptions) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ManifestIntegrityExemption, err error) {
	result = &v1.ManifestIntegrityExemption{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("manifestintegrityexemptions").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
