name: Unit Test

on: [pull_request]

jobs:
  lint:
    name: Run Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Test
        # the following 3 env variables are required for lint/tests
        run: |
          export ISHIELD_REPO_ROOT=$(pwd)
          export ISHIELD_ENV="local"
          export ISHIELD_TEST_ENV="local"
          make test-unit